### ISSUE TITLE
Show links on contact page

### ISSUE THREAD

**Issue by devonashleyberger** [devonashleyberger/contacts#54]

**Comment by tim-phillips** [comment]
`Links` component needs a list of links as strings, but we're getting a multiline text field from Airtable.

### Converting text to array

**text** (links, one per line)
"yahoo.com
google.com"

**array** of links
`['yahoo.com', 'google.com']`

- [ ] **Split** `text.split('\n')`

---

### Linking vs displaying the url

- [ ] **Linking** [normalize url](https://github.com/sindresorhus/normalize-url)
- [ ] **Display** as written
